'use client'

import { forwardRef } from 'react'
import type { CalculatedPersonSummary } from '@/lib/types'
import { getCurrencySymbol } from '@/lib/constants'

interface ExportTableProps {
  summaries: CalculatedPersonSummary[]
  currency: string
  billTitle: string
  grandTotal: number
  billDetails: {
    subtotal: number
    vat: number
    serviceCharge: number
    delivery: number
  }
  tipAmount?: number
  people: Array<{ id: string; color: string }>
}

export const ExportTable = forwardRef<HTMLDivElement, ExportTableProps>(
  ({ summaries, currency, billTitle, grandTotal, billDetails, tipAmount, people }, ref) => {
    const sym = getCurrencySymbol(currency)
    const getColor = (id: string) =>
      people.find((p) => p.id === id)?.color ?? '#6366f1'

    return (
      <div
        ref={ref}
        style={{
          position: 'absolute',
          left: '-9999px',
          top: 0,
          background: '#ffffff',
          padding: '24px',
          fontFamily: 'system-ui, -apple-system, sans-serif',
          color: '#111',
          width: 'max-content',
          minWidth: '420px',
        }}
      >
        <h2 style={{ margin: '0 0 4px', fontSize: '18px', fontWeight: 700 }}>
          {billTitle || 'Bill'} Summary
        </h2>
        <p style={{ margin: '0 0 16px', fontSize: '12px', color: '#666' }}>
          Generated by BillEase
        </p>

        <table
          style={{
            borderCollapse: 'collapse',
            width: '100%',
            fontSize: '13px',
          }}
        >
          <thead>
            <tr style={{ borderBottom: '2px solid #e5e7eb' }}>
              <th style={{ textAlign: 'left', padding: '8px 12px', whiteSpace: 'nowrap' }}>
                Person
              </th>
              <th style={{ textAlign: 'right', padding: '8px 12px', whiteSpace: 'nowrap' }}>
                Items
              </th>
              <th style={{ textAlign: 'right', padding: '8px 12px', whiteSpace: 'nowrap' }}>
                Shared
              </th>
              <th style={{ textAlign: 'right', padding: '8px 12px', whiteSpace: 'nowrap' }}>
                VAT
              </th>
              <th style={{ textAlign: 'right', padding: '8px 12px', whiteSpace: 'nowrap' }}>
                Service
              </th>
              {(tipAmount ?? 0) > 0 && (
                <th style={{ textAlign: 'right', padding: '8px 12px', whiteSpace: 'nowrap' }}>
                  Tip
                </th>
              )}
              <th
                style={{
                  textAlign: 'right',
                  padding: '8px 12px',
                  fontWeight: 700,
                  whiteSpace: 'nowrap',
                }}
              >
                Total Due
              </th>
            </tr>
          </thead>
          <tbody>
            {summaries.map((s, i) => {
              const sharedTotal =
                s.sharedItemsPortionValue +
                (s.customSharedPoolContributions?.reduce((a, c) => a + c.amount, 0) ?? 0)
              const tipShare =
                (tipAmount ?? 0) > 0 && summaries.length > 0
                  ? s.totalDue - s.itemsSubtotal - sharedTotal - s.vatShare - s.serviceChargeShare
                  : 0

              return (
                <tr
                  key={s.id}
                  style={{
                    borderBottom: '1px solid #f3f4f6',
                    background: i % 2 === 0 ? '#fafafa' : '#ffffff',
                  }}
                >
                  <td style={{ padding: '8px 12px', whiteSpace: 'nowrap' }}>
                    <span
                      style={{
                        display: 'inline-block',
                        width: '20px',
                        height: '20px',
                        borderRadius: '50%',
                        backgroundColor: getColor(s.id),
                        color: '#fff',
                        textAlign: 'center',
                        lineHeight: '20px',
                        fontSize: '11px',
                        fontWeight: 700,
                        marginRight: '8px',
                        verticalAlign: 'middle',
                      }}
                    >
                      {s.name[0]?.toUpperCase()}
                    </span>
                    {s.name}
                  </td>
                  <td style={{ textAlign: 'right', padding: '8px 12px' }}>
                    {sym} {s.itemsSubtotal.toFixed(2)}
                  </td>
                  <td style={{ textAlign: 'right', padding: '8px 12px' }}>
                    {sharedTotal > 0 ? `${sym} ${sharedTotal.toFixed(2)}` : '—'}
                  </td>
                  <td style={{ textAlign: 'right', padding: '8px 12px' }}>
                    {s.vatShare > 0 ? `${sym} ${s.vatShare.toFixed(2)}` : '—'}
                  </td>
                  <td style={{ textAlign: 'right', padding: '8px 12px' }}>
                    {s.serviceChargeShare > 0 ? `${sym} ${s.serviceChargeShare.toFixed(2)}` : '—'}
                  </td>
                  {(tipAmount ?? 0) > 0 && (
                    <td style={{ textAlign: 'right', padding: '8px 12px' }}>
                      {tipShare > 0 ? `${sym} ${tipShare.toFixed(2)}` : '—'}
                    </td>
                  )}
                  <td
                    style={{
                      textAlign: 'right',
                      padding: '8px 12px',
                      fontWeight: 700,
                    }}
                  >
                    {sym} {s.totalDue.toFixed(2)}
                  </td>
                </tr>
              )
            })}
          </tbody>
          <tfoot>
            <tr style={{ borderTop: '2px solid #e5e7eb' }}>
              <td
                style={{ padding: '8px 12px', fontWeight: 700 }}
                colSpan={(tipAmount ?? 0) > 0 ? 6 : 5}
              >
                Grand Total
              </td>
              <td
                style={{
                  textAlign: 'right',
                  padding: '8px 12px',
                  fontWeight: 700,
                  fontSize: '14px',
                }}
              >
                {sym} {grandTotal.toFixed(2)}
              </td>
            </tr>
          </tfoot>
        </table>

        {/* Sub-totals footer */}
        <div
          style={{
            display: 'flex',
            gap: '16px',
            flexWrap: 'wrap',
            marginTop: '12px',
            fontSize: '11px',
            color: '#666',
          }}
        >
          <span>Subtotal: {sym} {billDetails.subtotal.toFixed(2)}</span>
          <span>VAT: {sym} {billDetails.vat.toFixed(2)}</span>
          <span>Service: {sym} {billDetails.serviceCharge.toFixed(2)}</span>
          {billDetails.delivery > 0 && (
            <span>Delivery: {sym} {billDetails.delivery.toFixed(2)}</span>
          )}
          {(tipAmount ?? 0) > 0 && <span>Tip: {sym} {tipAmount!.toFixed(2)}</span>}
        </div>
      </div>
    )
  },
)

ExportTable.displayName = 'ExportTable'
